---
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: false

env:
  es6: true
  node: true
  mocha: true

extends: 'eslint:recommended'

plugins:
  - security

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  no-await-in-loop: error
  no-cond-assign: error
  no-console: error
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-empty: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: off
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations:
    - error
    - functions
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-prototype-builtins: off
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: off
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: off
  no-unsafe-negation: off
  use-isnan: error
  valid-jsdoc: off
  valid-typeof: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: off
  block-scoped-var: off
  class-methods-use-this: off
  complexity:
    - error
    - 6
  consistent-return: off
  curly: off
  default-case: off
  dot-location: off
  dot-notation: off
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: off
  no-empty-function: off
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: off
  no-fallthrough: error
  no-floating-decimal: off
  no-global-assign: off
  no-implicit-coercion: off
  no-implied-eval: error
  no-invalid-this: off
  no-iterator: error
  no-labels:
    - error
    - allowLoop: true
      allowSwitch: true
  no-lone-blocks: error
  no-loop-func: error
  no-magic-number: off
  no-multi-spaces: off
  no-multi-str: off
  no-native-reassign: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-octal: error
  no-param-reassign: off
  no-proto: error
  no-redeclare: error
  no-restricted-properties: off
  no-return-assign: error
  no-return-await: off
  no-script-url: error
  no-self-assign: off
  no-self-compare: error
  no-sequences: off
  no-throw-literal: off
  no-unmodified-loop-condition: off
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: off
  no-useless-return: off
  no-void: error
  no-warning-comments: off
  no-with: error
  prefer-promise-reject-errors: off
  radix: error
  require-await: off
  vars-on-top: off
  wrap-iife: error
  yoda: off

  # Strict
  strict: error

  # Variables
  init-declarations: off
  no-catch-shadow: off
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow-restricted-names: error
  no-shadow: off
  no-undef-init: error
  no-undef: off
  no-undefined: off
  no-unused-vars: error
  no-use-before-define: error

  # Node.js and CommonJS
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-mixed-requires: off
  no-new-require: off
  no-path-concat: error
  no-process-env: off
  no-process-exit: error
  no-restricted-modules: off
  no-sync: off

  # Stylistic Issues
  array-bracket-spacing: off
  block-spacing: off
  brace-style: off
  camelcase: warn
  capitalized-comments: warn
  comma-dangle:
    - error
    - never
  comma-spacing: off
  comma-style: off
  computed-property-spacing: off
  consistent-this: off
  eol-last: off
  func-call-spacing: off
  func-name-matching: off
  func-names: off
  func-style: warn
  id-length: off
  id-match: off
  indent:
    - error
    - 4
  jsx-quotes: off
  key-spacing: off
  keyword-spacing: off
  line-comment-position: off
  linebreak-style:
    - error
    - unix
  lines-around-comment: off
  lines-around-directive: off
  max-depth: off
  max-len: off
  max-nested-callbacks: off
  max-params: off
  max-statements-per-line: off
  max-statements:
    - error
    - 30
  multiline-ternary: off
  new-cap: off
  new-parens: off
  newline-after-var: off
  newline-before-return: off
  newline-per-chained-call: off
  no-array-constructor: off
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: off
  no-mixed-operators: off
  no-mixed-spaces-and-tabs: off
  no-multi-assign: off
  no-multiple-empty-lines: off
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: off
  no-plusplus: off
  no-restricted-syntax: off
  no-spaced-func: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: off
  no-unneeded-ternary: error
  object-curly-newline: off
  object-curly-spacing: off
  object-property-newline: off
  one-var-declaration-per-line: off
  one-var: off
  operator-assignment: off
  operator-linebreak: off
  padded-blocks: off
  quote-props: off
  quotes:
    - error
    - double
  require-jsdoc: error
  semi-spacing: off
  semi:
    - error
    - always
  sort-keys: off
  sort-vars: warn
  space-before-blocks: off
  space-before-function-paren: off
  space-in-parens: off
  space-infix-ops: off
  space-unary-ops: off
  spaced-comment: off
  template-tag-spacing: off
  unicode-bom: off
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: off
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-rest-params: off
  prefer-reflect: off
  prefer-spread: off
  prefer-template: off
  require-yield: off
  rest-spread-spacing: off
  sort-imports: warn
  symbol-description: off
  template-curly-spacing: off
  yield-star-spacing: off
  # https://github.com/nodesecurity/eslint-plugin-security#rules
  # detect-buffer-noassert: error
  # detect-child-process: error
  # detect-disable-mustache-escape: error
  # detect-eval-with-expression: error
  # detect-no-csrf-before-method-override: error
  # detect-non-literal-fs-filename: error
  # detect-non-literal-regexp: error
  # detect-non-literal-require: error
  # detect-object-injection: error
  # detect-possible-timing-attacks: error
  # detect-pseudoRandomBytes: error
  # detect-unsafe-regex: error
